name: Integrate

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-version: [prefer-lowest, prefer-stable]
        laravel: [ '10.*', '9.*', '8.*', '7.*', '6.*' ]
        php: [ '8.2', '8.1', '8.0', '7.4', '7.3', '7.2' ]
        include:
          - laravel: '10.*'
            testbench: '8.*'
          - laravel: '9.*'
            testbench: '7.*'
          - laravel: '8.*'
            testbench: '6.*'
          - laravel: '7.*'
            testbench: '5.*'
          - laravel: '6.*'
            testbench: '4.*'
        exclude:
          - laravel: '10.*'
            php: 8.0
          - laravel: '10.*'
            php: 7.4
          - laravel: '10.*'
            php: 7.3
          - laravel: '10.*'
            php: 7.2
          - laravel: '9.*'
            php: 7.4
          - laravel: '9.*'
            php: 7.4
          - laravel: '9.*'
            php: 7.3
          - laravel: '9.*'
            php: 7.2
          - laravel: '8.*'
            php: 8.2
          - laravel: '8.*'
            php: 7.2
          - laravel: '7.*'
            php: 8.2
          - laravel: '7.*'
            php: 8.1
          - laravel: '6.*'
            php: 8.2
          - laravel: '6.*'
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Run Test Suite
        run: "./vendor/bin/phpunit"
